on: push


jobs:

    run_tests:
      runs-on: ubuntu-latest
      steps:
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: pip install -r requirements.txt
      - uses: actions/checkout@v2
      - name: Run script file
        run: make test
